services:
  - type: web
    name: gerador-dr-antonio-api # Nome do serviço no Render.com
    env: python
    plan: free # Ou o plano pago que desejar
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.main:app --worker-tmp-dir /dev/shm"
    healthCheckPath: "/"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Ou a versão Python que preferir, ex: 3.9.12
      - key: FLASK_ENV 
        value: production # Garante que o Flask rode em modo de produção
      # Adicione outras variáveis de ambiente aqui se necessário
      # Exemplo: credenciais de banco de dados, chaves de API, etc.
      # - key: DATABASE_URL
      #   value: postgresql://user:password@host:port/database

